language: node_js
node_js: lts/*

sudo: required
services:
  - docker

before_install:
  - docker build -t adenijiazeez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adenijiazeez/react-test npm test -- --coverage

after_success:
  - docker build -t adenijiazeez/multi-client ./client
  - docker build -t adenijiazeez/multi-nginx ./nginx
  - docker build -t adenijiazeez/multi-server ./server
  - docker build -t adenijiazeez/multi-worker ./worker

# DOCKER LOGIN
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push image to dockerhub
- docker push adenijiazeez/multi-client
- docker push adenijiazeez/multi-nginx
- docker push adenijiazeez/multi-server
- docker push adenijiazeez/multi-worker
