apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    name: multi-docker-app
  name: nginx
spec:
  type: NodePort
  ports:
  - name: "nginx-service"
    port: 3050
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx
  
