apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    name: multi-docker-app
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: "nginx-service"
    port: 3050
    targetPort: 80
  selector:
    app: nginx
  
