apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    name: multi-docker-app
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: 6379
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 
