apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    name: multi-docker-app
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: adenijiazeez/multi_server
        name: server
        