apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    name: multi-docker-app
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: adenijiazeez/multi-worker
        name: worker
